# Site settings
title: Remembering Om Johari
email: remember.omjohari@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Memorial site for Om Johari (1940-2015)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://remember-omjohari.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
pagination: 5

# Build settings
markdown: kramdown

# Exclude post templates
exclude: post_templates
